Repository flipperdevices/flipperzero-firmware, pull requests merged in 2022-11, with the labels that each got.

#1951 fbt fixes for mfbt pt2
  .github/workflows/unit_tests.yml
  SConstruct
  applications/plugins/picopass/125_10px.png
  applications/plugins/picopass/application.fam
  applications/plugins/picopass/picopass_worker_i.h
  applications/plugins/picopass/rfal_picopass.c
  applications/services/gui/application.fam
  firmware.scons
  firmware/SConscript
  firmware/targets/f7/api_symbols.csv
  lib/SConscript
  lib/STM32CubeWB.scons
  lib/flipper_application/SConscript
  lib/flipper_format/SConscript
  lib/infrared/SConscript
  lib/lfrfid/SConscript
  lib/libusb_stm32.scons
  lib/mbedtls.scons
  lib/misc.scons
  lib/print/SConscript
  lib/subghz/SConscript
  lib/subghz/registry.h
  lib/toolbox/SConscript
  scripts/fbt/util.py
  scripts/fbt_tools/crosscc.py
  scripts/fbt_tools/fbt_apps.py
  scripts/fbt_tools/fbt_assets.py
  scripts/fbt_tools/fbt_dist.py
  scripts/fbt_tools/fbt_extapps.py
  scripts/fbt_tools/fbt_sdk.py
  scripts/fbt_tools/fbt_version.py
  scripts/fbt_tools/fwbin.py
  scripts/flipper/app.py
  scripts/sconsdist.py
  scripts/testing/await_flipper.py
  scripts/testing/units.py
  scripts/toolchain/fbtenv.cmd
  scripts/toolchain/fbtenv.sh
  scripts/toolchain/windows-toolchain-download.ps1
  site_scons/cc.scons
  site_scons/environ.scons
  site_scons/extapps.scons
Labels: build system, AppLoader

#1970 fbt: fixes for ufbt pt3
  SConstruct
  applications/main/bad_usb/application.fam
  applications/main/gpio/application.fam
  applications/main/ibutton/application.fam
  applications/main/infrared/application.fam
  applications/main/lfrfid/application.fam
  applications/main/u2f/application.fam
  debug/flipperapps.py
  fbt_options.py
  firmware.scons
  scripts/fbt/elfmanifest.py
  scripts/fbt/sdk/cache.py
  scripts/fbt_tools/fbt_assets.py
  scripts/fbt_tools/fbt_debugopts.py
  scripts/fbt_tools/fbt_dist.py
  scripts/fbt_tools/fbt_extapps.py
  scripts/requirements.txt
  site_scons/commandline.scons
  site_scons/environ.scons
  site_scons/extapps.scons
Labels: build system

#1965 infrared: add Kaseikyo IR protocol
  applications/debug/unit_tests/infrared/infrared_test.c
  assets/unit_tests/infrared/test_kaseikyo.irtest
  lib/infrared/encoder_decoder/common/infrared_common_protocol_defs.c
  lib/infrared/encoder_decoder/infrared.c
  lib/infrared/encoder_decoder/infrared.h
  lib/infrared/encoder_decoder/infrared_protocol_defs_i.h
  lib/infrared/encoder_decoder/kaseikyo/infrared_decoder_kaseikyo.c
  lib/infrared/encoder_decoder/kaseikyo/infrared_encoder_kaseikyo.c
  lib/infrared/encoder_decoder/kaseikyo/infrared_kaseikyo_spec.c
Labels: Infrared, new feature

#1995 fbt: 'target' field for apps; lib debugging support
  SConstruct
  documentation/AppManifests.md
  firmware.scons
  scripts/fbt/appmanifest.py
  scripts/fbt/util.py
  scripts/fbt_tools/fbt_apps.py
  scripts/fbt_tools/fbt_debugopts.py
  scripts/fbt_tools/fbt_sdk.py
  site_scons/commandline.scons
  site_scons/extapps.scons
Labels: build system

#1843 nfc: NTAG password auto capture (and other password-related changes)
  applications/main/nfc/scenes/nfc_scene_config.h
  applications/main/nfc/scenes/nfc_scene_mf_ultralight_menu.c
  applications/main/nfc/scenes/nfc_scene_mf_ultralight_read_auth.c
  applications/main/nfc/scenes/nfc_scene_mf_ultralight_read_auth_result.c
  applications/main/nfc/scenes/nfc_scene_mf_ultralight_unlock_auto.c
  applications/main/nfc/scenes/nfc_scene_mf_ultralight_unlock_menu.c
  applications/main/nfc/scenes/nfc_scene_mf_ultralight_unlock_warn.c
  applications/main/nfc/scenes/nfc_scene_nfc_data_info.c
  applications/main/nfc/scenes/nfc_scene_read.c
  applications/main/nfc/scenes/nfc_scene_saved_menu.c
  firmware/targets/f7/api_symbols.csv
  lib/nfc/nfc_device.c
  lib/nfc/nfc_device.h
  lib/nfc/nfc_worker.c
  lib/nfc/nfc_worker.h
  lib/nfc/protocols/mifare_ultralight.c
  lib/nfc/protocols/mifare_ultralight.h
Labels: NFC, new feature
