Repository flipperdevices/flipperzero-firmware, pull requests merged in 2024-05, with the labels that each got.

#3636 [FL-3813] Add the Akira animation
  assets/dolphin/external/L1_Akira_128x64/frame_0.png
  assets/dolphin/external/L1_Akira_128x64/frame_1.png
  assets/dolphin/external/L1_Akira_128x64/frame_10.png
  assets/dolphin/external/L1_Akira_128x64/frame_11.png
  assets/dolphin/external/L1_Akira_128x64/frame_12.png
  assets/dolphin/external/L1_Akira_128x64/frame_13.png
  assets/dolphin/external/L1_Akira_128x64/frame_14.png
  assets/dolphin/external/L1_Akira_128x64/frame_15.png
  assets/dolphin/external/L1_Akira_128x64/frame_16.png
  assets/dolphin/external/L1_Akira_128x64/frame_17.png
  assets/dolphin/external/L1_Akira_128x64/frame_18.png
  assets/dolphin/external/L1_Akira_128x64/frame_19.png
  assets/dolphin/external/L1_Akira_128x64/frame_2.png
  assets/dolphin/external/L1_Akira_128x64/frame_20.png
  assets/dolphin/external/L1_Akira_128x64/frame_21.png
  assets/dolphin/external/L1_Akira_128x64/frame_22.png
  assets/dolphin/external/L1_Akira_128x64/frame_23.png
  assets/dolphin/external/L1_Akira_128x64/frame_24.png
  assets/dolphin/external/L1_Akira_128x64/frame_25.png
  assets/dolphin/external/L1_Akira_128x64/frame_26.png
  assets/dolphin/external/L1_Akira_128x64/frame_27.png
  assets/dolphin/external/L1_Akira_128x64/frame_28.png
  assets/dolphin/external/L1_Akira_128x64/frame_29.png
  assets/dolphin/external/L1_Akira_128x64/frame_3.png
  assets/dolphin/external/L1_Akira_128x64/frame_30.png
  assets/dolphin/external/L1_Akira_128x64/frame_31.png
  assets/dolphin/external/L1_Akira_128x64/frame_32.png
  assets/dolphin/external/L1_Akira_128x64/frame_33.png
  assets/dolphin/external/L1_Akira_128x64/frame_34.png
  assets/dolphin/external/L1_Akira_128x64/frame_35.png
  assets/dolphin/external/L1_Akira_128x64/frame_4.png
  assets/dolphin/external/L1_Akira_128x64/frame_5.png
  assets/dolphin/external/L1_Akira_128x64/frame_6.png
  assets/dolphin/external/L1_Akira_128x64/frame_7.png
  assets/dolphin/external/L1_Akira_128x64/frame_8.png
  assets/dolphin/external/L1_Akira_128x64/frame_9.png
  assets/dolphin/external/L1_Akira_128x64/meta.txt
  assets/dolphin/external/manifest.txt
Labels: UI

#3631 Add support for `R_ARM_REL32` relocations.
  lib/flipper_application/elf/elf_file.c
Labels: New Feature, App Loader

#3647 FuriHal: move version init to early stage
  targets/f18/furi_hal/furi_hal.c
  targets/f7/furi_hal/furi_hal.c
Labels: Bug, Core+Services

#3644 Ble: new connection parameters negotiation scheme
  lib/ble_profile/extra_profiles/hid_profile.c
  targets/f7/ble_glue/gap.c
  targets/f7/ble_glue/profiles/serial_profile.c
Labels: Core+Services, Bluetooth

#3587 vscode: config fixes
  .vscode/example/clangd/extensions.json
  .vscode/example/cpptools/c_cpp_properties.json
Labels: Bug, Build System & Scripts

#3635 Infrared: Add Toshiba RAS-2518D
  applications/main/infrared/resources/infrared/assets/ac.ir
Labels: Infrared, New Feature

#3616 NFC: Mf Desfire fix reading big files
  applications/main/nfc/helpers/protocol_support/mf_desfire/mf_desfire_render.c
  lib/nfc/protocols/mf_desfire/mf_desfire_poller_i.c
Labels: NFC, Bug

#3640 Electra lfrfid protocol implementation
  lib/lfrfid/protocols/lfrfid_protocols.c
  lib/lfrfid/protocols/lfrfid_protocols.h
  lib/lfrfid/protocols/protocol_electra.c
  lib/lfrfid/protocols/protocol_electra.h
  lib/lfrfid/protocols/protocol_em4100.c
Labels: RFID 125kHz, New Feature

#3632 [FL-3797] Settings menu refactoring
  applications/services/gui/elements.h
  applications/services/gui/modules/submenu.c
  applications/services/gui/modules/submenu.h
  applications/settings/about/about.c
  applications/settings/bt_settings_app/scenes/bt_settings_scene_forget_dev_confirm.c
  applications/settings/bt_settings_app/scenes/bt_settings_scene_start.c
  applications/settings/desktop_settings/desktop_settings_app.c
  applications/settings/desktop_settings/desktop_settings_app.h
  applications/settings/desktop_settings/scenes/desktop_settings_scene_config.h
  applications/settings/desktop_settings/scenes/desktop_settings_scene_favorite.c
  applications/settings/desktop_settings/scenes/desktop_settings_scene_pin_menu.c
  applications/settings/desktop_settings/scenes/desktop_settings_scene_pin_setup.c
  applications/settings/desktop_settings/scenes/desktop_settings_scene_pin_setup_done.c
  applications/settings/desktop_settings/scenes/desktop_settings_scene_quick_apps_direction_menu.c
  applications/settings/desktop_settings/scenes/desktop_settings_scene_quick_apps_menu.c
  applications/settings/desktop_settings/scenes/desktop_settings_scene_start.c
  applications/settings/desktop_settings/views/desktop_settings_view_pin_setup_howto2.c
  applications/settings/power_settings_app/power_settings_app.h
  applications/settings/power_settings_app/scenes/power_settings_scene_config.h
  applications/settings/power_settings_app/scenes/power_settings_scene_power_off.c
  applications/settings/power_settings_app/scenes/power_settings_scene_reboot.c
  applications/settings/power_settings_app/scenes/power_settings_scene_reboot_confirm.c
  applications/settings/storage_settings/scenes/storage_settings_scene_benchmark.c
  applications/settings/storage_settings/scenes/storage_settings_scene_benchmark_confirm.c
  applications/settings/storage_settings/scenes/storage_settings_scene_config.h
  applications/settings/storage_settings/scenes/storage_settings_scene_factory_reset.c
  applications/settings/storage_settings/scenes/storage_settings_scene_formatting.c
  applications/settings/storage_settings/scenes/storage_settings_scene_internal_info.c
  applications/settings/storage_settings/scenes/storage_settings_scene_sd_info.c
  applications/settings/storage_settings/scenes/storage_settings_scene_start.c
  assets/icons/About/CertificationChina1_122x47.png
  assets/icons/About/CertificationChina1_124x47.png
  assets/icons/Settings/Cry_dolph_55x52.png
  assets/icons/Settings/LoadingHourglass_24x24.png
  assets/icons/Settings/dolph_cry_49x54.png
  assets/icons/Settings/qr_benchmark_25x25.png
  targets/f18/api_symbols.csv
  targets/f7/api_symbols.csv
Labels: UI

#3648 Add new map analyser
  .github/workflows/build.yml
  scripts/map_analyse_upload.py
  scripts/map_mariadb_insert.py
  scripts/map_parser.py
Labels: Build System & Scripts

#3315 Skylanders plugin
  applications/main/nfc/application.fam
  applications/main/nfc/plugins/supported_cards/skylanders.c
Labels: NFC

#3601 JS: Add submenu module
  applications/services/gui/application.fam
  applications/system/js_app/application.fam
  applications/system/js_app/examples/apps/Scripts/submenu.js
  applications/system/js_app/modules/js_submenu.c
  targets/f18/api_symbols.csv
  targets/f7/api_symbols.csv
Labels: New Feature, JS

#3598 JS: Add math module
  applications/system/js_app/application.fam
  applications/system/js_app/examples/apps/Scripts/math.js
  applications/system/js_app/js_thread.c
  applications/system/js_app/modules/js_math.c
  lib/mjs/mjs_core.c
Labels: New Feature, JS

#3597 JS: Add textbox module
  applications/system/js_app/application.fam
  applications/system/js_app/examples/apps/Scripts/textbox.js
  applications/system/js_app/modules/js_math.c
  applications/system/js_app/modules/js_textbox.c
Labels: New Feature, JS

#3655 Fix calling both `view_free_model()` and `view_free()`
  applications/services/gui/view.c
Labels: Bug, UI, Core+Services

#3642 [FL-3816] Text Box rework
  applications/debug/text_box_element_test/application.fam
  applications/debug/text_box_element_test/text_box_element_test.c
  applications/debug/text_box_view_test/application.fam
  applications/debug/text_box_view_test/text_box_view_test.c
  applications/services/gui/modules/text_box.c
Labels: UI, Core+Services

#3658 Text Box: fix displaying text with end text focus
  applications/debug/text_box_view_test/text_box_view_test.c
  applications/services/gui/modules/text_box.c
  targets/f7/furi_hal/furi_hal_flash.c
Labels: Bug, UI

#3659 [FL-3775] Archive: fix condition race on exit
  applications/main/archive/archive.c
  applications/main/archive/archive_i.h
  applications/main/archive/scenes/archive_scene_browser.c
Labels: Bug, Core+Services

#3660 Replaced obsolete-format delay
  targets/f7/furi_hal/furi_hal_flash.c
Labels: Core+Services

#3666 Electra non-initialized encoded epilogue on render fix
  lib/lfrfid/protocols/protocol_electra.c
Labels: RFID 125kHz, Bug

#3672 Furi: wrap message queue in container, prepare it for epoll. Accessor: disable expansion service on start.
  applications/debug/accessor/accessor_app.cpp
  applications/debug/accessor/accessor_app.h
  applications/system/snake_game/snake_game.c
  furi/core/message_queue.c
  furi/core/message_queue.h
Labels: New Feature, Core+Services
